source("API/DataReader.R")
source("API/ConductStatisticalTest.R")
print("hello")
n_iris_data <- DataReader$new("iris_tab.txt", seperator="\t")
c_iris_data_1 <- DataReader$new("corrupted-extended_iris_data_sets/iris_csv_big.csv")
c_iris_data_2 <- DataReader$new("corrupted-extended_iris_data_sets/iris_csv_purchase.csv")
c_iris_data_3 <- DataReader$new("corrupted-extended_iris_data_sets/iris_tab_bgnoise.txt", seperator = "\t")
# df <- read.table("iris_tab.txt", sep ="\t", header=TRUE)
# print(colnames(df))
#print(c_iris_data_1$list_of_column_data[["SepalLength"]])
n_iris_data_analyzer <- DataAnalyzer$new(n_iris_data)
c_iris_data_1_analyzer <- DataAnalyzer$new(c_iris_data_1)
c_iris_data_2_analyzer <- DataAnalyzer$new(c_iris_data_2)
c_iris_data_3_analyzer <- DataAnalyzer$new(c_iris_data_3)
print(c_iris_data_1$col_names)
print(c_iris_data_1$col_names[0])

print("Normal Data Set: ")
data1 <- n_iris_data_analyzer$conduct_one_way_anova_on("sepal_length", "species")
print(data1)
print("Corrupted Data Sets: ")
data2 <- c_iris_data_1_analyzer$conduct_one_way_anova_on("SepalLength", "Species")
data3 <- c_iris_data_2_analyzer$conduct_one_way_anova_on("sepal_width", "species")
data4 <- c_iris_data_3_analyzer$conduct_one_way_anova_on("sepal_length", "species")
print("data")
print(data2)
print(data3)
print(data4)